### ISSUE TITLE
`SnpArrays.filter` `min_maf` keyword argument not working?

### ISSUE THREAD

**Issue by mmkim1210** [OpenMendel/SnpArrays.jl#116]
In the below example, there are three SNPs that are non-polymorphic in the given set of samples, but these SNPs do not seem to be filtered out by the `min_maf = 0.05` argument in `SnpArrays.filter`. Is this a bug?

```julia
using SnpArrays

kgp = SnpData(joinpath(pwd(), "kgp")) # 4,966 SNPs
colinds = SnpArrays.filter(kgp.snparray; min_maf = 0.05)[2]
sum(colinds) # 4,966

n_unique = Int[]
for i in 1:size(kgp.snparray, 2)
    push!(n_unique, length(unique(view(kgp.snparray, :, i))))
end
count(x -> x == 1, n_unique) # 3
```
[kgp.zip](https://github.com/OpenMendel/SnpArrays.jl/files/7921877/kgp.zip)

**Comment by biona001** [comment]
It seems like all SNPs have MAF > 0.05 in your dataset
```julia
using SnpArrays
kgp = SnpData(joinpath(pwd(), "kgp")) # 4,966 SNPs
count(x -> x ≥ 0.05, maf(kgp.snparray)) # returns 4966
```
I'm not really sure what your second code block (starting with n_unique) is trying to do?

**Comment by biona001** [comment]
Oh, it seems like this might be a bug. There are 3 SNPs that are all 1s but their maf is somehow 0.5. 
```julia
using SnpArrays
kgp = SnpData(joinpath(pwd(), "kgp")) # 4,966 SNPs
x = convert(Matrix{Float64}, kgp.snparray)
idx = Int[]
for i in 1:size(kgp.snparray, 2)
    if length(unique(view(x, :, i))) == 1
        push!(idx, i)
    end
end
idx # 1229, 1230, 1231

mafs = maf(kgp.snparray)
mafs[idx] 
```

**Comment by mmkim1210** [comment]
yes, exactly!

**Comment by kose-y** [comment]
It sounds more like systematic variant calling problem than a bug with the `maf` function. 

```julia
julia> all(view(kgp.snparray, :, 1229) .== 0x02)
true
```
All the genotype values are `0x02`, and it means that both alleles are equally represented for the variant. Both alleles have allele frequency 0.5, so MAF is also 0.5. 

I have read from the PGEN format draft that it could be a sign of systematic variant calling problem if most of the calls are heterogeneous. Variants like these can be filtered based on "info score" or variance ratio (numeric variance divided by expected binomial variance `p(1-p)`).

**Comment by Hua-Zhou** [comment]
It's an interesting case. I agree with @kose-y that the MAF (=0.5) is calculated correctly, thus shouldn't be filtered by `min_maf = 0.05`. As a temporary solution, users can create a mask vector manually and filter by the mask vector.
