### ISSUE TITLE
Migrate to 0.6

### ISSUE THREAD

**Issue by kindlychung** [OpenMendel/SnpArrays.jl#12]
Now that julia0.6 has been released. :)

**Comment by Hua-Zhou** [comment]
Commit f793879 passes v0.6 test.

**Comment by kindlychung** [comment]
Ah, nice. 
I see lots of `@compat` there. Is this a temporary hack?

**Comment by Hua-Zhou** [comment]
Yes. `@compat` is for backward compatibility with v0.5. See 
https://github.com/JuliaLang/Compat.jl

**Comment by Hua-Zhou** [comment]
Closing since the package passes v0.6 build test now.
