### ISSUE TITLE
σinv calculated wrong in SnpBitMatrix

### ISSUE THREAD

**Issue by biona001** [OpenMendel/SnpArrays.jl#27]
The following example shows that σinv is not computed correctly in SnpBitMatrix.
```
#stupid function to simulate a random non-0 SnpArray
function simulate_random_snparray(
    n :: Int64,
    p :: Int64
)
    x_tmp = rand(0:2, n, p)
    x = SnpArray(undef, n, p)
    for i in 1:(n*p)
        if x_tmp[i] == 0
            x[i] = 0x00
        elseif x_tmp[i] == 1
            x[i] = 0x02
        else
            x[i] = 0x03
        end
    end
    return x
end
```
Compute the inverse standard deviation of a random SnpArray
```
using Random, SnpArrays
Random.seed!(1111)

x = simulate_random_snparray(100, 1)
xbm = SnpBitMatrix{Float64}(x, model=ADDITIVE_MODEL, center=true, scale=true);
xbm_vector = convert(Matrix{Float64}, x)

julia> xbm.σinv
1-element Array{Float64,1}:
 1.4159846508095772

julia> 1 / std(xbm_vector)
1.166543930706444
```

The following function computes the inverse standard deviation correctly, but I am not sure what's the best way to do this as well. 
```
function std_reciprocal(
    x        :: SnpBitMatrix, 
    mean_vec :: Vector{T}
) where {T <: Float64}
    m, n = size(x)
    @assert n == length(mean_vec) "number of columns of snpmatrix doesn't agree with length of mean vector"
    std_vector = zeros(T, n)

    @inbounds for j in 1:n
        @simd for i in 1:m
            a1 = x.B1[i, j]
            a2 = x.B2[i, j]
            std_vector[j] += (convert(T, a1 + a2) - mean_vec[j])^2
        end
        std_vector[j] = 1.0 / sqrt(std_vector[j] / (m - 1))
    end
    return std_vector
end

julia> std_reciprocal(xbm, xbm.μ)
1-element Array{Float64,1}:
 1.166543930706444
```

**Comment by kose-y** [comment]
The `σinv` field is based on the MLE of standard deviation from the model binomial distribution. It may be different from the sample standard deviation, especially when the actual distribution is far from the binomial distribution, as in this case. The MLE and sample standard deviation will be closer when `x` is actually sampled from a binomial distribution.

**Comment by biona001** [comment]
In that case what's the use of `σinv`? I thought the point of having `σinv` is to be able to standardize a `SnpBitMatrix`? I was following the standardization method of [this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5696071/pdf/nihms898446.pdf) (section 2.3.2).

**Comment by kose-y** [comment]
The current implementation follows the standardization method you mentioned using `σinv` and `\mu`. Sample standard deviation and MLE are just two different estimates for the standard deviation. The MLE is faster to compute and will be accurate if the distribution of SnpArray data follows binomial distribution.    
In your  `simulate_random_snparray`, the line `x_tmp = rand(0:2, n, p)` significantly breaks this assumption, as it samples data uniformly from {0, 1, 2}. You can see this if you try sampling `x_tmp` from Binomial(2, q) for some q \in (0,1), and compare the resulting sample standard deviation with `\sqrt{q * (1 - q/2)}` (true standard deviation) and `\sqrt{\mu * (1 - \mu/2)}` (the MLE).

I don't have much hands-on experience with SNP data, so I can't say much about if the data really follows the binomial distribution right now, but there is a good reason to believe so considering how the data is structured.

**Comment by Hua-Zhou** [comment]
In genetic literature, one scales a vector of SNPs by `sqrt(2p * (1 - p))`, where `p` is the minor allele frequency. This is how `σinv` is calculated in `SnpBitMatrix`. This is different from the usual sample standard deviation, as pointed out by @kose-y
