### ISSUE TITLE
default convert to Float64 returns backwards genotypes under additive model?

### ISSUE THREAD

**Issue by klkeys** [OpenMendel/SnpArrays.jl#3]
Shouldn't a `SnpArray` element `(true, true)` map to floating point `2.0` and `(false, false)` to floating point `0.0`? Currently the default `convert` to a `Matrix{Float64}` flips them. There appears to be no way for the user to convert to `Matrix{Float64}` with a specification for `minor_allele`, unlike `convert` for the Boolean tuples (currently line 150 of SnpArrays.jl).

Minimal working example:

    srand(2016);
    z = SnpArray(rand(0:2, 5, 3));
    Z = convert(Matrix{Float64}, z);
    display(z)
    display(Z)

Output for `z`:

    5x3 SnpArrays.SnpArray{2}:
    (false,true)   (false,true)  (true,true) 
    (false,false)  (true,true)   (true,true) 
    (true,true)    (true,true)   (true,true) 
    (true,true)    (false,true)  (false,true)
    (false,true)   (false,true)  (false,true)

Output for `Z`:

    5x3 Array{Float64,2}:
     1.0  1.0  0.0
     2.0  0.0  0.0
     0.0  0.0  0.0
     0.0  1.0  1.0
     1.0  1.0  1.0

**Comment by Hua-Zhou** [comment]
Following PLINK convention, `true` refers to a copy of A2 allele. When converting to real numbers for analysis purpose, we almost always want the real number to be *minor allele* count. That’s how  the `convert` method works. It first figures out which is the minor allele for each column, then translate the minor allele counts into real number. In your example, the first SNP has 6 A1 allele and 3 A2 allele, so A2 is the minor allele. Therefore first column of Z is the A1 counts. Similar for other columns.

**Comment by klkeys** [comment]
But per Issue #2, this renders multiplication inconsistent. For simplicity, let us neither center nor scale the multiplication. Continuing the aforementioned MWE:

    y = ones(3);
    x1 = z.A1*y + z.A2*y;
    x2 = Z*y;
    display(x1)
    display(x2)

Output for `x1`:

    5-element Array{Float64,1}:
     4.0
     4.0
     6.0
     4.0
     3.0

Output for `x2`:

    5-element Array{Float64,1}:
     2.0
     2.0
     0.0
     2.0
     3.0

**Comment by klkeys** [comment]
Wait, your previous comment is backwards. If `true` represents a copy of the A2 allele, then column 1 of `z` has six **A2** alleles and three **A1** alleles. Then A1 is the minor allele, which explains the behavior of `convert`. But this is still inconsistent since, as you say, PLINK conventions count copies of the A2 allele, and here `convert` explicitly breaks that convention.

**Comment by Hua-Zhou** [comment]
Your are right my previous comment is backwards. In your first column there are 3 A1 alleles and 6 A2 alleles, therefore A1 is the minor allele. Therefore convert method translated to count of  A1 alleles. I would keep the convention that convert always translates to minor allele counts (versus the A2 allele count) since it’s the most use cases.

**Comment by Hua-Zhou** [comment]
We should keep the convert/copy methods as it is (translating to minor allele counts). When overloading the multiplication methods, a BitVector of minor_allele should be utilized for correct implementation if we intend to multiply the minor allele count matrix.

**Comment by klkeys** [comment]
Currently there is no `convert` method with an argument to specify minor alleles.

**Comment by Hua-Zhou** [comment]
Convert figures out which is the minor allele itself so doesn’t need the minor allele input. Multiplication methods should take that information though.
