### ISSUE TITLE
unsafe creation of SnpData from Plink file

### ISSUE THREAD

**Issue by Hua-Zhou** [OpenMendel/SnpArrays.jl#36]
@kose-y When creating SnpData from Plink files, 
https://github.com/OpenMendel/SnpArrays.jl/blob/4e10a6b0db27637e1d977d92c7baa579f43c9803/src/snpdata.jl#L23
the `CSV.read` function opens the bim function without closing it. A safer way is
```julia
snp_info = open(plink_bim_fike) do io
    categorial!(CSV.read(io,  delim='\t', header=SNP_INFO_KEYS, 
    types=[String, String, Float64, Int, String, String]), [:allele1, :allele2])
end
```

Need to check the `readdlm` function as well
https://github.com/OpenMendel/SnpArrays.jl/blob/4e10a6b0db27637e1d977d92c7baa579f43c9803/src/snpdata.jl#L30
May be safer to use
```julia
person_info = open(plink_fam_file) do io
    DataFrame(readdlm(io, AbstractString))
end
```

**Comment by kose-y** [comment]
@Hua-Zhou Thank you for pointing this out. I checked the source of `readdlm` and it is safe.
