### ISSUE TITLE
*.bed files are opened RW for reading.

### ISSUE THREAD

**Issue by msuchard** [OpenMendel/SnpArrays.jl#5]
Unfortunately, this modifies the date.

**Comment by Hua-Zhou** [comment]
@ericsobel  Can you provide a minimal reproducible example? I just ran ` Pkg.test("SnpArrays")` and the [tutorial example](https://github.com/OpenMendel/SnpArrays.jl/blob/master/docs/snparray.ipynb). The date of bed file remains unchanged.

**Comment by Hua-Zhou** [comment]
Commit c14a17e applies mmap to the IOStream, which is opened with -r.
https://github.com/OpenMendel/SnpArrays.jl/blob/c14a17eb5f9be50e062ceffe462fd5bf88cfe374/src/SnpArrays.jl#L57
Should fix the date modification behavior.
