### ISSUE TITLE
Pkg.clone format listed requires public/private key

### ISSUE THREAD

**Issue by jcpapp** [OpenMendel/SnpArrays.jl#6]
I think the format you list in your documentation under installation
Pkg.clone("git@github.com:OpenMendel/SnpArrays.jl.git")
requires a public/private key set-up with github.

I think the alternate format
Pkg.clone("https://github.com/OpenMendel/SnpArrays.jl.git")
would be better. It has the same basic functionality and can be run by anyone. Of course, since it does not require a public/private key, it is not as secure.

**Comment by Hua-Zhou** [comment]
Good catch @jcpapp 

It's fixed in the documentation now https://openmendel.github.io/SnpArrays.jl/latest/#installation
