### ISSUE TITLE
Mean imputation for linear algebra?

### ISSUE THREAD

**Issue by kose-y** [OpenMendel/SnpArrays.jl#67]
Currently, linear algebra routines impute any missing value with zero. I know it's going to be a performance killer, but isn't imputing it with the mean more natural?

**Comment by Hua-Zhou** [comment]
If it can be done efficiently, certainly I prefer imputation by mean.

**Comment by kose-y** [comment]
@Hua-Zhou Quick benchmark says that mean imputation is 25-30% slower than zero imputation on CPU (still twice as fast as single-threaded BLAS) and is not slower on GPU. Should I make it a default behavior?

**Comment by Hua-Zhou** [comment]
Yes please make it default. Please also update the function
documentation and package documentation.

**Comment by kose-y** [comment]
OK. I will finish it off today.
