### ISSUE TITLE
feature request: copyto!(v, s) for SnpBitMatrix and SnpLinAlg

### ISSUE THREAD

**Issue by biona001** [OpenMendel/SnpArrays.jl#81]
Is there some reason `copyto!` doesn't exist for `SnpBitMatrix` and `SnpLinAlg`? If they simply haven't been implemented, I can try to do it. I have an application where I want only a few SNPs to multiply a vector, so I figured copying them into a small matrix would be the easiest.

**Comment by kose-y** [comment]
It's simply not implemented. Should we consider the implementation of SnpLinAlg x AbstractVector?

**Comment by biona001** [comment]
Yeah, I need `Xb`. I guess I will try to implement `copyto!` for `SnpBitMatrix` and `SnpLinAlg`, unless I find a simpler way to extract a few SNPs.

**Comment by Hua-Zhou** [comment]
It's good addition to have `copyto!` for both `SnpBitMatrix` and
`SnpLinAlg`.

**Comment by kose-y** [comment]
For `SnpLinAlg`, it should be as simple as calling `copyto!` with the underlying `SnpArray`.

**Comment by kose-y** [comment]
resolved in #82

**Comment by biona001** [comment]
For some reason [travis](https://travis-ci.org/github/OpenMendel/SnpArrays.jl) now fails on Julia 1.5, but on the `copyto` branch it clearly passes? What's going on

**Comment by kose-y** [comment]
```
norm(convert(Matrix{t}, EUR, model = model) * v2) < reltol
  AssertionError: For performance reasons, `BitArray{N}` where `N > 1` are required to have a multiple of 8 rows.
```

When was this restriction introduced?

**Comment by kose-y** [comment]
See #83. I am closing this issue, as our new problem is unrelated to the topic of this issue.
