### ISSUE TITLE
Breaking change from VectorizationBase.jl

### ISSUE THREAD

**Issue by kose-y** [OpenMendel/SnpArrays.jl#83]
https://github.com/chriselrod/VectorizationBase.jl/blob/49fbee294124d1f1771b9c3cf2b86bfeb3332456/src/strided_pointers/stridedpointers.jl#L238

The package VectorizationBase.jl introduced a breaking change that only allows multiple of 8 rows in `BitMatrix`es. That disallows the usage of the newly-introduced `mul!()` function here. https://github.com/OpenMendel/SnpArrays.jl/blob/master/src/linalg_bitmatrix.jl#L154

I can think of three ways to resolve this issue. Which way should we use?

1. Zero-pad SnpBitMatrix to always have multiple of 8 rows on BitArray representation
2. Remove VectorizationBase-related routines, and revert to older versions
3. Use VectorizationBase-related routines only when we have a multiple of 8 rows

**Comment by kose-y** [comment]
For now, upper-bounding the version of VectorizationBase. https://github.com/OpenMendel/SnpArrays.jl/commit/2bf0011c3b66c9b7f95ea34deb068d23993f840a

**Comment by biona001** [comment]
Actually, I initially thought `SnpLinAlg` is meant to replace SnpBitMatrix? How about we just delete SnpBitMatrix related routines?

**Comment by kose-y** [comment]
Yes, `SnpLinAlg` is intended to eventually replace `SnpBitMatrix`. `SnpBitMatrix` will eventually be removed. 

Maybe we don't need to fix this issue and remove SnpBitMatrix for the next minor release.  We should patch-release the current state (upper bounding the version of VectorizationBase) before that.

We need to keep in mind that this will break any program that uses `SnpBitMatrix`.

**Comment by kose-y** [comment]
@Hua-Zhou What is your opinion on deprecating or removing `SnpBitMatrix`?

**Comment by Hua-Zhou** [comment]
The whole purpose of `SnpBitMatrix` is for efficient linear algebra without
expanding into a float point matrix. If this can be achieved now using just
`SnpArray` with similar or even better efficiency, I'm totally fine with
deprecating `SnpBitMatrix`.

**Comment by kose-y** [comment]
Then let's deprecate `SnpBitMatrix` for the next patch release (v0.3.5 - to be released right after deprecation), and then remove it for the next minor release (v0.4.0). 

Do we have a timeline for release?

**Comment by biona001** [comment]
Sounds good to me. I'm going to update IHT in a few days so it won't affect me, although I'm not sure how many people are using SnpBitMatrix other than myself.

**Comment by kose-y** [comment]
I searched all GitHub with "SnpBitMatrix", and I got this package, MendelIHT, tutorial materials, and [this line from TraitSimulation.jl](https://github.com/OpenMendel/TraitSimulation.jl/blob/6d1f09c7332471a74b4dd6c8ef2d2b95a96c585c/src/modelframework.jl#L147).

**Comment by kose-y** [comment]
v0.3.5 is now released. Its lifetime is expected to be very short, as it cannot run on julia nightly due to the upper bound on the `VectorizationBase` package. `master` branch will have `SnpBitMatrix` removed soon.

**Comment by kose-y** [comment]
v0.3.6 released. It removes the upper bound for VectorizationBase. SnpBitMatrix is still there with LoopVectorization-based parts removed.
