### ISSUE TITLE
No manifest.toml?

### ISSUE THREAD

**Issue by biona001** [OpenMendel/SnpArrays.jl#92]
Why is there not a manifest.toml file? Is this intentional?

**Comment by kose-y** [comment]
Yes, this is intentional. Manifest.toml is not really necessary for this package because...

- This package does not include code for experiments where reproducibility is important.
- It does not depend on any non-registered packages.

**Comment by biona001** [comment]
Ah ok. But when (if?) my SnpLinAlg-matrix mul gets merged, it'll require VectorizationBase version >0.20.18 and LoopVectorization version > 0.12.42. Do I just change that in project.toml then?

**Comment by kose-y** [comment]
Yes, the minimum version for each registered package can be defined in Project.toml.
